### ISSUE TITLE
There is no fact #1

### ISSUE THREAD

**Issue by Katatje** [DarkiBoi/CliNet#5]
private static String facts = "2: Animals that lay eggs don't have belly buttons.?" +
            "3: Beavers can hold their breath for 45 minutes under water.?" +
            "4: Slugs have four noses.?" + ...

there is no fact 1
help

**Comment by DarkiBoi** [comment]
o no :(

**Comment by ghost** [comment]
:(

**Comment by DarkiBoi** [comment]
https://www.snapple.com/real-facts doesnt have fact 1

**Comment by ghost** [comment]
yoink facts!
